import type { Problem } from './types'
import { enrichProblems } from '../lib/problemLatex'

export type DiagnosticQuestionKind = 'procedural' | 'choice' | 'graph' | 'error_identification'

export interface DiagnosticMixSpec {
  skillId: string
  kind: DiagnosticQuestionKind
  title: string
  prompt: string
  expectedAnswer: string
  answerType: 'expression' | 'text' | 'choice'
  choices?: string[]
  difficulty: number
  hintSequence: string[]
}

const MIX: DiagnosticMixSpec[] = [
  {
    skillId: 'chain_rule',
    kind: 'choice',
    title: 'Method selection',
    prompt: 'Which rule applies to d/dx [sin(x²)]?',
    expectedAnswer: 'chain rule',
    answerType: 'choice',
    choices: ['chain rule', 'product rule', 'quotient rule', 'power rule only'],
    difficulty: 0.35,
    hintSequence: ['Look for a function inside another function.'],
  },
  {
    skillId: 'chain_rule',
    kind: 'error_identification',
    title: 'Spot the mistake',
    prompt: 'A student writes d/dx [sin(x²)] = cos(x²). What went wrong?',
    expectedAnswer: 'missing inner derivative',
    answerType: 'text',
    difficulty: 0.4,
    hintSequence: ['Did they multiply by the derivative of the inner function?'],
  },
  {
    skillId: 'limits_intro',
    kind: 'choice',
    title: 'Limit concept',
    prompt: 'What does lim(x→2) f(x) describe?',
    expectedAnswer: 'approaching value',
    answerType: 'choice',
    choices: ['approaching value', 'f(2) always', 'average slope', 'area under curve'],
    difficulty: 0.3,
    hintSequence: ['Limits describe behavior near a point, not necessarily at it.'],
  },
  {
    skillId: 'extrema',
    kind: 'graph',
    title: 'Graph interpretation',
    prompt: "If f′(x) changes from + to − at x=3, what happens at x=3?",
    expectedAnswer: 'local maximum',
    answerType: 'choice',
    choices: ['local maximum', 'local minimum', 'inflection point', 'discontinuity'],
    difficulty: 0.42,
    hintSequence: ['Sign change in the first derivative signals an extremum.'],
  },
  {
    skillId: 'series_test_selection',
    kind: 'choice',
    title: 'Series test',
    prompt: 'Best first test for ∑ 1/n²?',
    expectedAnswer: 'p-series',
    answerType: 'choice',
    choices: ['p-series', 'ratio test', 'alternating series test', 'root test'],
    difficulty: 0.38,
    hintSequence: ['Match the general term form to a standard test.'],
  },
  {
    skillId: 'u_substitution',
    kind: 'error_identification',
    title: 'Setup check',
    prompt: 'A student sets u = x² but leaves ∫ cos(u) du without changing dx. What is missing?',
    expectedAnswer: 'du substitution',
    answerType: 'text',
    difficulty: 0.36,
    hintSequence: ['u-sub requires replacing dx with du (including constants).'],
  },
  {
    skillId: 'related_rates',
    kind: 'graph',
    title: 'Related rates model',
    prompt: 'A balloon radius increases. Which pair is related by differentiation?',
    expectedAnswer: 'dr/dt and dV/dt',
    answerType: 'choice',
    choices: ['dr/dt and dV/dt', 'V and t only', 'A and x', 'none'],
    difficulty: 0.4,
    hintSequence: ['Write V(r(t)) then differentiate with respect to time.'],
  },
  {
    skillId: 'integration_by_parts',
    kind: 'choice',
    title: 'Parts selection',
    prompt: 'For ∫ x e^x dx, which is a good u?',
    expectedAnswer: 'u = x',
    answerType: 'choice',
    choices: ['u = x', 'u = e^x', 'u = 1', 'u = x e^x'],
    difficulty: 0.37,
    hintSequence: ['LIATE: choose u to simplify when differentiated.'],
  },
  {
    skillId: 'derivative_rules_basic',
    kind: 'choice',
    title: 'Power rule',
    prompt: 'What is d/dx [5x^4]?',
    expectedAnswer: '20x^3',
    answerType: 'choice',
    choices: ['20x^3', '5x^3', '20x^4', '4x^3'],
    difficulty: 0.28,
    hintSequence: ['Multiply the exponent down and subtract one from the power.'],
  },
  {
    skillId: 'function_composition',
    kind: 'error_identification',
    title: 'Composition setup',
    prompt: 'A student writes f(g(x)) = f(x)·g(x). What concept did they confuse?',
    expectedAnswer: 'composition',
    answerType: 'text',
    difficulty: 0.32,
    hintSequence: ['Composition nests one output inside another — it is not multiplication.'],
  },
  {
    skillId: 'function_notation',
    kind: 'choice',
    title: 'Function notation',
    prompt: 'If f(x) = 2x + 1, what does f(3) mean?',
    expectedAnswer: 'evaluate at 3',
    answerType: 'choice',
    choices: ['evaluate at 3', 'multiply f by 3', 'derivative at 3', 'inverse of f'],
    difficulty: 0.25,
    hintSequence: ['The input replaces x in the rule.'],
  },
  {
    skillId: 'implicit_differentiation',
    kind: 'graph',
    title: 'Implicit curve',
    prompt: 'For x² + y² = 25, the slope dy/dx at (3, 4) is:',
    expectedAnswer: '-3/4',
    answerType: 'choice',
    choices: ['-3/4', '3/4', '4/3', '0'],
    difficulty: 0.44,
    hintSequence: ['Differentiate both sides with respect to x and solve for dy/dx.'],
  },
  {
    skillId: 'optimization',
    kind: 'choice',
    title: 'Optimization step',
    prompt: 'After writing a constraint equation, what is the usual next step?',
    expectedAnswer: 'express one variable',
    answerType: 'choice',
    choices: ['express one variable', 'integrate immediately', 'take second derivative test only', 'graph only'],
    difficulty: 0.38,
    hintSequence: ['Reduce to a single-variable function before finding critical points.'],
  },
  {
    skillId: 'ftc',
    kind: 'choice',
    title: 'FTC link',
    prompt: 'The Fundamental Theorem connects antiderivatives to:',
    expectedAnswer: 'definite integrals',
    answerType: 'choice',
    choices: ['definite integrals', 'limits only', 'series convergence', 'polar coordinates'],
    difficulty: 0.35,
    hintSequence: ['FTC evaluates definite integrals using antiderivatives.'],
  },
  {
    skillId: 'power_series',
    kind: 'error_identification',
    title: 'Radius reasoning',
    prompt: 'A student says a power series converges for all x because the first terms look small. What is missing?',
    expectedAnswer: 'ratio test',
    answerType: 'text',
    difficulty: 0.41,
    hintSequence: ['You need a test on the general term or ratio of coefficients.'],
  },
  {
    skillId: 'exponents_radicals',
    kind: 'error_identification',
    title: 'Exponent mistake',
    prompt: 'A student writes (x^2)^(1/2) = x^2. What rule did they misuse?',
    expectedAnswer: 'power of a power',
    answerType: 'text',
    difficulty: 0.3,
    hintSequence: ['Multiply exponents when raising a power to a power.'],
  },
  {
    skillId: 'logarithms',
    kind: 'choice',
    title: 'Log concept',
    prompt: 'log(ab) equals:',
    expectedAnswer: 'log(a) + log(b)',
    answerType: 'choice',
    choices: ['log(a) + log(b)', 'log(a) log(b)', 'log(a)/log(b)', 'log(a+b)'],
    difficulty: 0.32,
    hintSequence: ['Product rule for logarithms.'],
  },
  {
    skillId: 'inverse_functions',
    kind: 'choice',
    title: 'Inverse concept',
    prompt: 'The graph of f^(-1) is the reflection of f across:',
    expectedAnswer: 'y = x',
    answerType: 'choice',
    choices: ['y = x', 'x-axis', 'y-axis', 'origin'],
    difficulty: 0.28,
    hintSequence: ['Swap x and y coordinates.'],
  },
  {
    skillId: 'graph_interpretation',
    kind: 'graph',
    title: 'Graph reading',
    prompt: 'Where f′(x) = 0 and f′ changes sign, you expect:',
    expectedAnswer: 'local extremum',
    answerType: 'choice',
    choices: ['local extremum', 'vertical asymptote', 'discontinuity', 'inflection only'],
    difficulty: 0.34,
    hintSequence: ['Critical points with sign change indicate extrema.'],
  },
  {
    skillId: 'transformations',
    kind: 'choice',
    title: 'Shift direction',
    prompt: 'f(x - 2) shifts the graph of f:',
    expectedAnswer: 'right 2',
    answerType: 'choice',
    choices: ['right 2', 'left 2', 'up 2', 'down 2'],
    difficulty: 0.28,
    hintSequence: ['x - 2 inside means horizontal shift right.'],
  },
  {
    skillId: 'trig_identities_calc',
    kind: 'error_identification',
    title: 'Identity slip',
    prompt: 'A student claims sin(2x) = 2 sin(x). Which identity fixes this?',
    expectedAnswer: 'double angle',
    answerType: 'text',
    difficulty: 0.34,
    hintSequence: ['sin(2x) = 2 sin(x) cos(x).'],
  },
  {
    skillId: 'word_problem_translation',
    kind: 'choice',
    title: 'Setup step',
    prompt: 'Before solving a related-rates problem, you should first:',
    expectedAnswer: 'draw and label',
    answerType: 'choice',
    choices: ['draw and label', 'integrate', 'apply L\'Hopital', 'find Taylor series'],
    difficulty: 0.3,
    hintSequence: ['Sketch the situation and name variables.'],
  },
  {
    skillId: 'inverse_trig_derivatives',
    kind: 'choice',
    title: 'Inverse trig method',
    prompt: 'd/dx [arcsin(3x)] requires:',
    expectedAnswer: 'chain rule',
    answerType: 'choice',
    choices: ['chain rule', 'product rule only', 'quotient rule only', 'no chain rule'],
    difficulty: 0.38,
    hintSequence: ['Inner function 3x needs its derivative.'],
  },
  {
    skillId: 'first_derivative_test',
    kind: 'graph',
    title: 'First derivative sign',
    prompt: "If f′ is positive then negative around x = c, f has a:",
    expectedAnswer: 'local maximum',
    answerType: 'choice',
    choices: ['local maximum', 'local minimum', 'inflection', 'asymptote'],
    difficulty: 0.36,
    hintSequence: ['+ to − on f′ means decreasing after increasing.'],
  },
  {
    skillId: 'second_derivative_test',
    kind: 'choice',
    title: 'Second derivative test',
    prompt: 'At a critical point, f′′(c) < 0 implies:',
    expectedAnswer: 'local maximum',
    answerType: 'choice',
    choices: ['local maximum', 'local minimum', 'no conclusion', 'inflection'],
    difficulty: 0.37,
    hintSequence: ['Concave down at c → local max.'],
  },
  {
    skillId: 'area_net_change',
    kind: 'choice',
    title: 'Net change',
    prompt: '∫_0^T v(t) dt for velocity v gives:',
    expectedAnswer: 'displacement',
    answerType: 'choice',
    choices: ['displacement', 'average speed only', 'acceleration', 'curvature'],
    difficulty: 0.33,
    hintSequence: ['Integral of velocity is net displacement.'],
  },
  {
    skillId: 'numerical_integration',
    kind: 'choice',
    title: 'Method selection',
    prompt: 'When function values are easy to sample but no antiderivative is known, use:',
    expectedAnswer: 'numerical integration',
    answerType: 'choice',
    choices: ['numerical integration', 'partial fractions', 'ratio test', 'implicit differentiation'],
    difficulty: 0.32,
    hintSequence: ['Trapezoid/Simpson approximate the integral.'],
  },
  {
    skillId: 'work_applications',
    kind: 'error_identification',
    title: 'Work setup',
    prompt: 'A student uses W = Fd with changing force F(x). What is missing?',
    expectedAnswer: 'integral',
    answerType: 'text',
    difficulty: 0.36,
    hintSequence: ['Variable force requires ∫ F(x) dx.'],
  },
  {
    skillId: 'exponential_growth',
    kind: 'choice',
    title: 'Growth model',
    prompt: 'dy/dt = ky models:',
    expectedAnswer: 'exponential growth',
    answerType: 'choice',
    choices: ['exponential growth', 'linear growth', 'constant population', 'geometric series'],
    difficulty: 0.34,
    hintSequence: ['Proportional to current amount → exponential.'],
  },
  {
    skillId: 'telescoping_series',
    kind: 'choice',
    title: 'Telescoping recognition',
    prompt: 'Series ∑ (1/n - 1/(n+1)) is best evaluated by:',
    expectedAnswer: 'telescoping',
    answerType: 'choice',
    choices: ['telescoping', 'ratio test', 'root test only', 'L\'Hopital'],
    difficulty: 0.36,
    hintSequence: ['Partial sums collapse.'],
  },
  {
    skillId: 'root_test',
    kind: 'choice',
    title: 'Root vs ratio',
    prompt: 'For a_n = (p/q)^n, which test is often quickest?',
    expectedAnswer: 'root test',
    answerType: 'choice',
    choices: ['root test', 'integral test', 'alternating series test', 'comparison to harmonic'],
    difficulty: 0.35,
    hintSequence: ['nth root of r^n is |r|.'],
  },
  {
    skillId: 'absolute_convergence',
    kind: 'error_identification',
    title: 'Rearrangement error',
    prompt: 'A student rearranges terms of the alternating harmonic series to make it diverge. The series was:',
    expectedAnswer: 'conditionally convergent',
    answerType: 'text',
    difficulty: 0.4,
    hintSequence: ['Only absolutely convergent series can be rearranged freely.'],
  },
  {
    skillId: 'surface_area',
    kind: 'choice',
    title: 'Surface vs volume',
    prompt: 'Surface area of revolution uses the element ds. Volume of revolution typically uses:',
    expectedAnswer: 'dx or dy',
    answerType: 'choice',
    choices: ['dx or dy', 'dθ only', 'no integration', 'second derivative'],
    difficulty: 0.38,
    hintSequence: ['Volume integrates cross-section area; surface uses arc length element.'],
  },
  {
    skillId: 'rates_units',
    kind: 'error_identification',
    title: 'Units check',
    prompt: 'A rate is given in ft/s but distance needed in miles. What step is missing?',
    expectedAnswer: 'unit conversion',
    answerType: 'text',
    difficulty: 0.28,
    hintSequence: ['Convert units before combining quantities.'],
  },
  {
    skillId: 'exponential_functions',
    kind: 'graph',
    title: 'Exponential graph',
    prompt: 'y = 2^x passes through (0, ?):',
    expectedAnswer: '1',
    answerType: 'choice',
    choices: ['1', '0', '2', 'e'],
    difficulty: 0.26,
    hintSequence: ['Any a^x passes through (0, 1).'],
  },
  {
    skillId: 'derivatives_exp_log',
    kind: 'choice',
    title: 'Log derivative',
    prompt: 'd/dx [ln(3x)] equals:',
    expectedAnswer: '1/x',
    answerType: 'choice',
    choices: ['1/x', '1/(3x)', '3/x', 'ln(3)'],
    difficulty: 0.36,
    hintSequence: ['ln(3x) = ln(3) + ln(x); derivative of ln(x) is 1/x.'],
  },
  {
    skillId: 'concavity',
    kind: 'graph',
    title: 'Concavity graph',
    prompt: 'If f′′(x) > 0 on an interval, the graph is:',
    expectedAnswer: 'concave up',
    answerType: 'choice',
    choices: ['concave up', 'concave down', 'decreasing', 'linear'],
    difficulty: 0.34,
    hintSequence: ['f′′ > 0 means slope increasing.'],
  },
  {
    skillId: 'partial_fractions',
    kind: 'choice',
    title: 'Partial fractions cue',
    prompt: '∫ (x+1)/((x-1)(x+2)) dx suggests:',
    expectedAnswer: 'partial fractions',
    answerType: 'choice',
    choices: ['partial fractions', 'u-sub only', 'ratio test', 'Newton\'s method'],
    difficulty: 0.37,
    hintSequence: ['Rational function with factorable denominator.'],
  },
  {
    skillId: 'algebra_manipulation',
    kind: 'choice',
    title: 'Prerequisite check',
    prompt: 'Before applying quotient rule, you typically need solid?',
    expectedAnswer: 'algebra manipulation',
    answerType: 'choice',
    choices: ['algebra manipulation', 'series tests', 'polar coordinates', 'FTC part 2'],
    difficulty: 0.24,
    hintSequence: ['Simplifying products and powers supports derivative rules.'],
  },
  {
    skillId: 'trig_values',
    kind: 'choice',
    title: 'Prerequisite check',
    prompt: 'sin(π/6) equals?',
    expectedAnswer: '1/2',
    answerType: 'choice',
    choices: ['1/2', 'sqrt(3)/2', '1', '0'],
    difficulty: 0.26,
    hintSequence: ['Unit circle value at 30°.'],
  },
  {
    skillId: 'derivative_definition',
    kind: 'error_identification',
    title: 'Limit setup',
    prompt: 'A student uses (f(x)-f(a))/(x+a) for the derivative at a. What is wrong?',
    expectedAnswer: 'wrong denominator',
    answerType: 'text',
    difficulty: 0.38,
    hintSequence: ['Definition uses x − a in the denominator.'],
  },
  {
    skillId: 'definite_integrals',
    kind: 'graph',
    title: 'Signed area',
    prompt: 'If f(x) < 0 on [a,b], then ∫_a^b f(x) dx is:',
    expectedAnswer: 'negative',
    answerType: 'choice',
    choices: ['negative', 'positive', 'zero always', 'undefined'],
    difficulty: 0.33,
    hintSequence: ['Integral accumulates signed area.'],
  },
  {
    skillId: 'antiderivatives',
    kind: 'choice',
    title: 'Prerequisite check',
    prompt: 'Every antiderivative of f differs by?',
    expectedAnswer: 'constant',
    answerType: 'choice',
    choices: ['constant', 'x', 'factor of 2', 'nothing'],
    difficulty: 0.28,
    hintSequence: ['Indefinite integrals include +C.'],
  },
  {
    skillId: 'lhopital',
    kind: 'choice',
    title: 'Method selection',
    prompt: 'lim (sin x)/x as x→0 is indeterminate form?',
    expectedAnswer: '0/0',
    answerType: 'choice',
    choices: ['0/0', '∞/∞', 'not indeterminate', '1/0'],
    difficulty: 0.34,
    hintSequence: ['Both numerator and denominator approach 0.'],
  },
  {
    skillId: 'geometric_series',
    kind: 'error_identification',
    title: 'Series mistake',
    prompt: 'A student sums ∑ (1/2)^n from n=0 to ∞ as 1/2. They forgot?',
    expectedAnswer: 'first term a',
    answerType: 'text',
    difficulty: 0.36,
    hintSequence: ['Formula a/(1-r) needs correct leading term.'],
  },
  {
    skillId: 'taylor_series',
    kind: 'choice',
    title: 'Concept check',
    prompt: 'Taylor coefficients use derivatives evaluated at?',
    expectedAnswer: 'center a',
    answerType: 'choice',
    choices: ['center a', 'x only', 'infinity', 'endpoint b only'],
    difficulty: 0.37,
    hintSequence: ['Series is centered at a.'],
  },
  {
    skillId: 'related_rates',
    kind: 'error_identification',
    title: 'Prerequisite chain',
    prompt: 'Related rates fails if you skip implicit differentiation with respect to?',
    expectedAnswer: 'time',
    answerType: 'text',
    difficulty: 0.35,
    hintSequence: ['Differentiate with respect to t.'],
  },
  {
    skillId: 'curve_sketching',
    kind: 'graph',
    title: 'Sketch synthesis',
    prompt: 'To sketch f, you combine sign charts for f′ and f″ with?',
    expectedAnswer: 'intercepts',
    answerType: 'choice',
    choices: ['intercepts', 'ratio test', 'partial fractions', 'polar area only'],
    difficulty: 0.4,
    hintSequence: ['Critical points, concavity, and intercepts together.'],
  },
  {
    skillId: 'infinite_limits',
    kind: 'choice',
    title: 'Asymptote concept',
    prompt: 'Vertical asymptote at x=a often means lim f(x) as x→a is?',
    expectedAnswer: 'infinite',
    answerType: 'choice',
    choices: ['infinite', 'zero', 'f(a)', 'does not exist only'],
    difficulty: 0.32,
    hintSequence: ['Unbounded behavior near a.'],
  },
  {
    skillId: 'riemann_sums',
    kind: 'graph',
    title: 'Riemann visualization',
    prompt: 'Left Riemann sum uses sample height at each subinterval\'s?',
    expectedAnswer: 'left endpoint',
    answerType: 'choice',
    choices: ['left endpoint', 'right endpoint', 'midpoint only', 'maximum'],
    difficulty: 0.3,
    hintSequence: ['Left sum: evaluate at left end of each piece.'],
  },
  {
    skillId: 'trig_substitution',
    kind: 'choice',
    title: 'Method selection',
    prompt: '∫ sqrt(9-x^2) dx suggests substitution x = ?',
    expectedAnswer: '3 sin(theta)',
    answerType: 'choice',
    choices: ['3 sin(theta)', '3 sec(theta)', 'x^2', 'tan(x)'],
    difficulty: 0.41,
    hintSequence: ['Match a²−x² pattern with a sin θ.'],
  },
  {
    skillId: 'parametric_equations',
    kind: 'choice',
    title: 'Parametric concept',
    prompt: 'Eliminating parameter t gives curve in?',
    expectedAnswer: 'xy plane',
    answerType: 'choice',
    choices: ['xy plane', 't axis only', 'polar plane only', 'complex plane'],
    difficulty: 0.3,
    hintSequence: ['x(t) and y(t) describe a plane curve.'],
  },
  {
    skillId: 'polar_arc_length',
    kind: 'choice',
    title: 'Polar arc setup',
    prompt: 'Polar arc length integrates with respect to?',
    expectedAnswer: 'theta',
    answerType: 'choice',
    choices: ['theta', 'x only', 'n', 't always'],
    difficulty: 0.38,
    hintSequence: ['Polar curves use angle parameter θ.'],
  },
]

export function diagnosticMixForSkills(skillIds: string[]): Problem[] {
  const set = new Set(skillIds)
  return enrichProblems(
    MIX.filter((spec) => set.has(spec.skillId)).map((spec, index) => ({
      id: `diag-mix-${spec.skillId}-${spec.kind}-${index}`,
      title: spec.title,
      prompt: spec.prompt,
      skillIds: [spec.skillId],
      difficulty: spec.difficulty,
      mode: 'diagnostic' as const,
      answerType: spec.answerType,
      expectedAnswer: spec.expectedAnswer,
      choices: spec.choices,
      hintSequence: spec.hintSequence,
      verificationStatus: 'verified' as const,
      source: `diagnostic_${spec.kind}`,
    })),
  )
}

export function inferDiagnosticQuestionKind(problem: Problem): DiagnosticQuestionKind {
  if (problem.source?.includes('error_identification')) return 'error_identification'
  if (problem.source?.includes('graph') || problem.source === 'diagnostic_graph') return 'graph'
  if (problem.answerType === 'choice' || problem.source?.includes('choice')) return 'choice'
  return 'procedural'
}
