import type { InlineShortcutDefinitions } from 'mathlive'

/**
 * Calculus-focused inline shortcuts merged with MathLive defaults in MathInput.
 * Keys are typed in order; a brief pause or delimiter completes multi-char shortcuts.
 */
export const MATHPILOT_INLINE_SHORTCUTS: InlineShortcutDefinitions = {
  sqrt: '\\sqrt{#0}',
  cbrt: '\\sqrt[3]{#0}',
  root: '\\sqrt{#0}',
  abs: '\\left|#0\\right|',
  norm: '\\left\\lVert#0\\right\\rVert',
  oo: '\\infty',
  infty: '\\infty',
  inf: '\\infty',
  pi: '\\pi',
  theta: '\\theta',
  alpha: '\\alpha',
  beta: '\\beta',
  gamma: '\\gamma',
  delta: '\\delta',
  lambda: '\\lambda',
  mu: '\\mu',
  sigma: '\\sigma',
  epsilon: '\\epsilon',
  phi: '\\phi',
  omega: '\\omega',
  partial: '\\partial',
  nabla: '\\nabla',
  cdot: '\\cdot',
  times: '\\times',
  pm: '\\pm',
  mp: '\\mp',
  leq: '\\leq',
  geq: '\\geq',
  neq: '\\neq',
  approx: '\\approx',
  equiv: '\\equiv',
  sin: '\\sin',
  cos: '\\cos',
  tan: '\\tan',
  sec: '\\sec',
  csc: '\\csc',
  cot: '\\cot',
  arcsin: '\\arcsin',
  arccos: '\\arccos',
  arctan: '\\arctan',
  sinh: '\\sinh',
  cosh: '\\cosh',
  tanh: '\\tanh',
  log: '\\log',
  ln: '\\ln',
  lg: '\\lg',
  exp: '\\exp',
  lim: '\\lim_{#0}',
  int: '\\int',
  iint: '\\iint',
  iiint: '\\iiint',
  oint: '\\oint',
  sum: '\\sum',
  prod: '\\prod',
  vec: '\\vec{#0}',
  hat: '\\hat{#0}',
  bar: '\\bar{#0}',
  dot: '\\dot{#0}',
  ddot: '\\ddot{#0}',
  overline: '\\overline{#0}',
  underline: '\\underline{#0}',
  text: { value: '\\text{#0}', after: 'space | nothing | binop | relop | punct | openfence | closefence' },
  dx: { value: '\\,dx', after: 'closefence | digit | letter' },
  dy: { value: '\\,dy', after: 'closefence | digit | letter' },
  dt: { value: '\\,dt', after: 'closefence | digit | letter' },
  du: { value: '\\,du', after: 'closefence | digit | letter' },
  dv: { value: '\\,dv', after: 'closefence | digit | letter' },
}

export function mergeMathInlineShortcuts(
  defaults: InlineShortcutDefinitions,
): InlineShortcutDefinitions {
  return { ...defaults, ...MATHPILOT_INLINE_SHORTCUTS }
}
